// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: atcoder.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAtcoderSubmissionsRaw = `-- name: CreateAtcoderSubmissionsRaw :exec
INSERT INTO atcoder_submissions (user_id, submission_id, problem_id, point, status, at)
SELECT
	unnest($1::bigint[]),
	unnest($2::bigint[]),
	unnest($3::varchar[]),
	unnest($4::double precision[]),
	unnest($5::varchar[]),
	unnest($6::timestamptz[])
`

type CreateAtcoderSubmissionsRawParams struct {
	Column1 []int64              `json:"column_1"`
	Column2 []int64              `json:"column_2"`
	Column3 []string             `json:"column_3"`
	Column4 []float64            `json:"column_4"`
	Column5 []string             `json:"column_5"`
	Column6 []pgtype.Timestamptz `json:"column_6"`
}

func (q *Queries) CreateAtcoderSubmissionsRaw(ctx context.Context, arg CreateAtcoderSubmissionsRawParams) error {
	_, err := q.db.Exec(ctx, createAtcoderSubmissionsRaw,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
	)
	return err
}

const createAtcoderUserRaw = `-- name: CreateAtcoderUserRaw :one
INSERT INTO atcoder_users (username, avatar_url, rank, rating, highest_rating, promotion_message, submission_statistics)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, username, avatar_url, rank, rating, highest_rating, promotion_message, submission_statistics
`

type CreateAtcoderUserRawParams struct {
	Username             string `json:"username"`
	AvatarUrl            string `json:"avatar_url"`
	Rank                 string `json:"rank"`
	Rating               int32  `json:"rating"`
	HighestRating        int32  `json:"highest_rating"`
	PromotionMessage     string `json:"promotion_message"`
	SubmissionStatistics []byte `json:"submission_statistics"`
}

func (q *Queries) CreateAtcoderUserRaw(ctx context.Context, arg CreateAtcoderUserRawParams) (AtcoderUser, error) {
	row := q.db.QueryRow(ctx, createAtcoderUserRaw,
		arg.Username,
		arg.AvatarUrl,
		arg.Rank,
		arg.Rating,
		arg.HighestRating,
		arg.PromotionMessage,
		arg.SubmissionStatistics,
	)
	var i AtcoderUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.AvatarUrl,
		&i.Rank,
		&i.Rating,
		&i.HighestRating,
		&i.PromotionMessage,
		&i.SubmissionStatistics,
	)
	return i, err
}

const getAtcoderSubmissionsAfter = `-- name: GetAtcoderSubmissionsAfter :many
SELECT id, user_id, submission_id, problem_id, point, status, at FROM atcoder_submissions WHERE user_id = $1 AND at > $2 ORDER BY id ASC
`

type GetAtcoderSubmissionsAfterParams struct {
	UserID int64              `json:"user_id"`
	At     pgtype.Timestamptz `json:"at"`
}

func (q *Queries) GetAtcoderSubmissionsAfter(ctx context.Context, arg GetAtcoderSubmissionsAfterParams) ([]AtcoderSubmission, error) {
	rows, err := q.db.Query(ctx, getAtcoderSubmissionsAfter, arg.UserID, arg.At)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AtcoderSubmission
	for rows.Next() {
		var i AtcoderSubmission
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SubmissionID,
			&i.ProblemID,
			&i.Point,
			&i.Status,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAtcoderUserByIDRaw = `-- name: GetAtcoderUserByIDRaw :one
SELECT id, username, avatar_url, rank, rating, highest_rating, promotion_message, submission_statistics FROM atcoder_users WHERE id = $1
`

func (q *Queries) GetAtcoderUserByIDRaw(ctx context.Context, id int64) (AtcoderUser, error) {
	row := q.db.QueryRow(ctx, getAtcoderUserByIDRaw, id)
	var i AtcoderUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.AvatarUrl,
		&i.Rank,
		&i.Rating,
		&i.HighestRating,
		&i.PromotionMessage,
		&i.SubmissionStatistics,
	)
	return i, err
}

const getAtcoderUserByUsernameRaw = `-- name: GetAtcoderUserByUsernameRaw :one
SELECT id, username, avatar_url, rank, rating, highest_rating, promotion_message, submission_statistics FROM atcoder_users WHERE username = $1
`

func (q *Queries) GetAtcoderUserByUsernameRaw(ctx context.Context, username string) (AtcoderUser, error) {
	row := q.db.QueryRow(ctx, getAtcoderUserByUsernameRaw, username)
	var i AtcoderUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.AvatarUrl,
		&i.Rank,
		&i.Rating,
		&i.HighestRating,
		&i.PromotionMessage,
		&i.SubmissionStatistics,
	)
	return i, err
}

const updateAtcoderSubmissionStatisticsRaw = `-- name: UpdateAtcoderSubmissionStatisticsRaw :exec
UPDATE atcoder_users SET submission_statistics = $2 WHERE id = $1 returning id, username, avatar_url, rank, rating, highest_rating, promotion_message, submission_statistics
`

type UpdateAtcoderSubmissionStatisticsRawParams struct {
	ID                   int64  `json:"id"`
	SubmissionStatistics []byte `json:"submission_statistics"`
}

func (q *Queries) UpdateAtcoderSubmissionStatisticsRaw(ctx context.Context, arg UpdateAtcoderSubmissionStatisticsRawParams) error {
	_, err := q.db.Exec(ctx, updateAtcoderSubmissionStatisticsRaw, arg.ID, arg.SubmissionStatistics)
	return err
}
