// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: codeforces.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCodeforcesSubmissionsRaw = `-- name: CreateCodeforcesSubmissionsRaw :exec
INSERT INTO codeforces_submissions (user_id, problem, status, at)
SELECT unnest($1::bigint[]), unnest($2::jsonb[]), unnest($3::varchar[]), unnest($4::timestamptz[])
`

type CreateCodeforcesSubmissionsRawParams struct {
	Column1 []int64              `json:"column_1"`
	Column2 [][]byte             `json:"column_2"`
	Column3 []string             `json:"column_3"`
	Column4 []pgtype.Timestamptz `json:"column_4"`
}

func (q *Queries) CreateCodeforcesSubmissionsRaw(ctx context.Context, arg CreateCodeforcesSubmissionsRawParams) error {
	_, err := q.db.Exec(ctx, createCodeforcesSubmissionsRaw,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	return err
}

const createCodeforcesUserRaw = `-- name: CreateCodeforcesUserRaw :one
INSERT INTO codeforces_users (username, avatar_url, friend_num, rating_records, submission_statistics) VALUES ($1, $2, $3, $4, $5) RETURNING id, username, avatar_url, friend_num, rating_records, submission_statistics
`

type CreateCodeforcesUserRawParams struct {
	Username             string `json:"username"`
	AvatarUrl            string `json:"avatar_url"`
	FriendNum            int32  `json:"friend_num"`
	RatingRecords        []byte `json:"rating_records"`
	SubmissionStatistics []byte `json:"submission_statistics"`
}

func (q *Queries) CreateCodeforcesUserRaw(ctx context.Context, arg CreateCodeforcesUserRawParams) (CodeforcesUser, error) {
	row := q.db.QueryRow(ctx, createCodeforcesUserRaw,
		arg.Username,
		arg.AvatarUrl,
		arg.FriendNum,
		arg.RatingRecords,
		arg.SubmissionStatistics,
	)
	var i CodeforcesUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.AvatarUrl,
		&i.FriendNum,
		&i.RatingRecords,
		&i.SubmissionStatistics,
	)
	return i, err
}

const getCodeforcesSubmissionsAfter = `-- name: GetCodeforcesSubmissionsAfter :many
SELECT id, user_id, problem, status, at FROM codeforces_submissions WHERE user_id = $1 AND at > $2 ORDER BY id ASC
`

type GetCodeforcesSubmissionsAfterParams struct {
	UserID int64              `json:"user_id"`
	At     pgtype.Timestamptz `json:"at"`
}

func (q *Queries) GetCodeforcesSubmissionsAfter(ctx context.Context, arg GetCodeforcesSubmissionsAfterParams) ([]CodeforcesSubmission, error) {
	rows, err := q.db.Query(ctx, getCodeforcesSubmissionsAfter, arg.UserID, arg.At)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CodeforcesSubmission
	for rows.Next() {
		var i CodeforcesSubmission
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Problem,
			&i.Status,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCodeforcesUserByIDRaw = `-- name: GetCodeforcesUserByIDRaw :one
SELECT id, username, avatar_url, friend_num, rating_records, submission_statistics FROM codeforces_users where id = $1
`

func (q *Queries) GetCodeforcesUserByIDRaw(ctx context.Context, id int64) (CodeforcesUser, error) {
	row := q.db.QueryRow(ctx, getCodeforcesUserByIDRaw, id)
	var i CodeforcesUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.AvatarUrl,
		&i.FriendNum,
		&i.RatingRecords,
		&i.SubmissionStatistics,
	)
	return i, err
}

const getCodeforcesUserByUsernameRaw = `-- name: GetCodeforcesUserByUsernameRaw :one
SELECT id, username, avatar_url, friend_num, rating_records, submission_statistics FROM codeforces_users where username = $1
`

func (q *Queries) GetCodeforcesUserByUsernameRaw(ctx context.Context, username string) (CodeforcesUser, error) {
	row := q.db.QueryRow(ctx, getCodeforcesUserByUsernameRaw, username)
	var i CodeforcesUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.AvatarUrl,
		&i.FriendNum,
		&i.RatingRecords,
		&i.SubmissionStatistics,
	)
	return i, err
}

const getCodeforcesUserLastSubmission = `-- name: GetCodeforcesUserLastSubmission :one
SELECT id, user_id, problem, status, at FROM codeforces_submissions WHERE user_id = $1 ORDER BY id DESC LIMIT 1
`

func (q *Queries) GetCodeforcesUserLastSubmission(ctx context.Context, userID int64) (CodeforcesSubmission, error) {
	row := q.db.QueryRow(ctx, getCodeforcesUserLastSubmission, userID)
	var i CodeforcesSubmission
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Problem,
		&i.Status,
		&i.At,
	)
	return i, err
}

const updateCodeforcesRatingRecordsRaw = `-- name: UpdateCodeforcesRatingRecordsRaw :exec
UPDATE codeforces_users SET rating_records = $2 WHERE id = $1 returning id, username, avatar_url, friend_num, rating_records, submission_statistics
`

type UpdateCodeforcesRatingRecordsRawParams struct {
	ID            int64  `json:"id"`
	RatingRecords []byte `json:"rating_records"`
}

func (q *Queries) UpdateCodeforcesRatingRecordsRaw(ctx context.Context, arg UpdateCodeforcesRatingRecordsRawParams) error {
	_, err := q.db.Exec(ctx, updateCodeforcesRatingRecordsRaw, arg.ID, arg.RatingRecords)
	return err
}

const updateCodeforcesSubmissionStatisticsRaw = `-- name: UpdateCodeforcesSubmissionStatisticsRaw :exec
UPDATE codeforces_users SET submission_statistics = $2 WHERE id = $1 returning id, username, avatar_url, friend_num, rating_records, submission_statistics
`

type UpdateCodeforcesSubmissionStatisticsRawParams struct {
	ID                   int64  `json:"id"`
	SubmissionStatistics []byte `json:"submission_statistics"`
}

func (q *Queries) UpdateCodeforcesSubmissionStatisticsRaw(ctx context.Context, arg UpdateCodeforcesSubmissionStatisticsRawParams) error {
	_, err := q.db.Exec(ctx, updateCodeforcesSubmissionStatisticsRaw, arg.ID, arg.SubmissionStatistics)
	return err
}
