// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AtcoderSubmission struct {
	ID           int64              `json:"id"`
	UserID       int64              `json:"user_id"`
	SubmissionID int64              `json:"submission_id"`
	ProblemID    string             `json:"problem_id"`
	Point        float64            `json:"point"`
	Status       string             `json:"status"`
	At           pgtype.Timestamptz `json:"at"`
}

type AtcoderUser struct {
	ID                   int64  `json:"id"`
	Username             string `json:"username"`
	AvatarUrl            string `json:"avatar_url"`
	Rank                 string `json:"rank"`
	Rating               int32  `json:"rating"`
	HighestRating        int32  `json:"highest_rating"`
	PromotionMessage     string `json:"promotion_message"`
	SubmissionStatistics []byte `json:"submission_statistics"`
}

type CodeforcesSubmission struct {
	ID      int64              `json:"id"`
	UserID  int64              `json:"user_id"`
	Problem []byte             `json:"problem"`
	Status  string             `json:"status"`
	At      pgtype.Timestamptz `json:"at"`
}

type CodeforcesUser struct {
	ID                   int64  `json:"id"`
	Username             string `json:"username"`
	AvatarUrl            string `json:"avatar_url"`
	FriendNum            int32  `json:"friend_num"`
	RatingRecords        []byte `json:"rating_records"`
	SubmissionStatistics []byte `json:"submission_statistics"`
}

type Race struct {
	ID        int64              `json:"id"`
	Races     []byte             `json:"races"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
