// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateCodeforcesSubmissionsRaw(ctx context.Context, arg CreateCodeforcesSubmissionsRawParams) error
	CreateCodeforcesUserRaw(ctx context.Context, arg CreateCodeforcesUserRawParams) (CodeforcesUser, error)
	CreateRaceRaw(ctx context.Context, races []byte) error
	GetCodeforcesSubmissionsAfter(ctx context.Context, arg GetCodeforcesSubmissionsAfterParams) ([]CodeforcesSubmission, error)
	GetCodeforcesUserByID(ctx context.Context, id int64) (CodeforcesUser, error)
	GetCodeforcesUserByUsername(ctx context.Context, username string) (CodeforcesUser, error)
	GetCodeforcesUserLastSubmission(ctx context.Context, userID int64) (CodeforcesSubmission, error)
	GetLastRaceCreatedAt(ctx context.Context) (pgtype.Timestamptz, error)
	GetLastRaceRaw(ctx context.Context) ([]byte, error)
	UpdateCodeforcesRatingRecordsRaw(ctx context.Context, arg UpdateCodeforcesRatingRecordsRawParams) error
	UpdateCodeforcesSubmissionStatisticsRaw(ctx context.Context, arg UpdateCodeforcesSubmissionStatisticsRawParams) error
}

var _ Querier = (*Queries)(nil)
