// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: race.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRaceRaw = `-- name: CreateRaceRaw :exec
insert into races (races) values ($1)
`

func (q *Queries) CreateRaceRaw(ctx context.Context, races []byte) error {
	_, err := q.db.Exec(ctx, createRaceRaw, races)
	return err
}

const getLastRaceCreatedAt = `-- name: GetLastRaceCreatedAt :one
select created_at from races order by created_at desc limit 1
`

func (q *Queries) GetLastRaceCreatedAt(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getLastRaceCreatedAt)
	var created_at pgtype.Timestamptz
	err := row.Scan(&created_at)
	return created_at, err
}

const getLastRaceRaw = `-- name: GetLastRaceRaw :one
select races from races order by created_at desc limit 1
`

func (q *Queries) GetLastRaceRaw(ctx context.Context) ([]byte, error) {
	row := q.db.QueryRow(ctx, getLastRaceRaw)
	var races []byte
	err := row.Scan(&races)
	return races, err
}
